name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧪 Tests"
    labels:
      - "test"
      - "tests"
  - title: "📖 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "maintenance"
      - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "documentation"
      - "chore"
      - "maintenance"
      - "dependencies"
  default: patch
autolabeler:
  - label: "fix"
    title:
      - "/^fix(\\(.+\\))?[!:]?\\s/i"
      - "/^bug(\\(.+\\))?[!:]?\\s/i"
  - label: "feature"
    title:
      - "/^feat(\\(.+\\))?[!:]?\\s/i"
      - "/^feature(\\(.+\\))?[!:]?\\s/i"
      - "/^add(\\(.+\\))?[!:]?\\s/i"
  - label: "documentation"
    title:
      - "/^docs?(\\(.+\\))?[!:]?\\s/i"
  - label: "chore"
    title:
      - "/^chore(\\(.+\\))?[!:]?\\s/i"
      - "/^ci(\\(.+\\))?[!:]?\\s/i"
      - "/^build(\\(.+\\))?[!:]?\\s/i"
      - "/^refactor(\\(.+\\))?[!:]?\\s/i"
template: |
  ## Changes

  $CHANGES
